### PR TITLE
Add bug number bsc#956917

### PR DESCRIPTION
**Pull request by imobach**
Add bug number for https://github.com/yast/yast-services-manager/pull/109 because SR was [declined](https://build.suse.de/request/show/82641).

### CODE REVIEW

**Comment by mchf** [comment]
LGTM

**Comment by ancorgs** [comment]
Submit requests to TW/SP2 also require bug number? That's kind of weird.

**Comment by lslezak** [comment]
@ancorgs I guess it's a general SLE policy...

LGTM

**Comment by imobach** [comment]
Thanks guys.

**Comment by ancorgs** [comment]
Well, I guess is reasonable for SP2 (it's a service pack, after all), but kind of annoying for development in master.

**Comment by jreidinger** [comment]
yes, I also agree it is very annoying. So I start using fake bugs and they start complaining :) https://build.opensuse.org/request/show/345904

**Pull request merged**
