### PR TITLE
[WIP] AutoYaST X11 test

### PR DESCRIPTION
**Pull request by lslezak**
- Proposed fix for https://bugzilla.suse.com/show_bug.cgi?id=1046083
- Completely **untested**!
- No unit tests (so far)!

### CODE REVIEW

**Comment by kobliha** [comment]
This is going to break with SLE 15 where we might use either Wayland or X11

From my POV, we should try to set the graphical target if requested, if that fails (graphical target is not available) then we should at least set text-mode, and THEN inform the user.

**Comment by kobliha** [comment]
But it's "good as a hotfix"

**Comment by lslezak** [comment]
The "xorg-x11-server" assumption is used at more places, we need to grep whole YaST for the correct Wayland support. But that's out of scope for this SP3 hot fix.

**Comment by lslezak** [comment]
I'm not sure if we want it in SLE15-GA, it's not that urgent (you can fix your AY profile to include the X11 packages or switch to the text mode default).

I'd postpone it for SLE15-SP1 (and add a Wayland support).

**Comment by schubi2** [comment]
This PR has be replaced by
https://github.com/yast/yast-services-manager/pull/187

**Pull request closed without merging**
