### PR TITLE
Fixing bug #103

### PR DESCRIPTION
**Pull request by crojasaragonez**
Fixing issue => https://github.com/yast/yast-services-manager/issues/103

### CODE REVIEW

**Comment by jreidinger** [comment]
LGTM

**Comment by kobliha** [comment]
@jreidinger You have to merge it yourself :) @crojasaragonez doesn't have enough perms for that.

**Comment by jreidinger** [comment]
ok, lets merge it

**Comment by crojasaragonez** [comment]
Thanks @jreidinger @kobliha

**Pull request merged**
